<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Models\Entities\Product.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Unity" Version="5.11.10" />
    <PackageReference Include="Unity.Abstractions" Version="5.11.7" />
    <PackageReference Include="Unity.Container" Version="5.11.11" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Tests\" />
  </ItemGroup>

</Project>
